
##############################################################
# AUTOGENERATED - DO NOT ADD OR EDIT FILES IN THIS DIRECTORY
# AS CHANGES WILL BE OVERWRITTEN!
#
# See bin/enable-namespacing.py for additional documentation
##############################################################


from lib_utils.namespace import extend_namespace
extend_namespace(__file__, __path__, __name__, [    "../src/core/python",
    "../src/not-core/python",])
